create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports rst]
set_input_delay -clock [get_clocks clk] -max -add_delay 4.000 [get_ports rst]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports {stall[*]}]
set_output_delay -clock [get_clocks clk] -max -add_delay 4.000 [get_ports {stall[*]}]
