webtalk_init -webtalk_dir /run/media/sudhar/D-Drive/Spider/VLSI/RV32IM/RV32IM.sim/sim_1/behav/xsim/xsim.dir/RV32Core_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 11 17:54:15 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "39046ab5-fd62-4192-9a70-e1b6903fc44d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f6c30cac3f97498fb9cd4f820e7edb28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "141" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2485.400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "22" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "145 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "12 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "161" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "25" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "398740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4009688914 -regid "" -xml /run/media/sudhar/D-Drive/Spider/VLSI/RV32IM/RV32IM.sim/sim_1/behav/xsim/xsim.dir/RV32Core_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /run/media/sudhar/D-Drive/Spider/VLSI/RV32IM/RV32IM.sim/sim_1/behav/xsim/xsim.dir/RV32Core_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /run/media/sudhar/D-Drive/Spider/VLSI/RV32IM/RV32IM.sim/sim_1/behav/xsim/xsim.dir/RV32Core_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
