@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Oct 16 16:47:47 +0530 2020
=======
REM Generated by Vivado on Sat Oct 17 18:59:22 +0400 2020
>>>>>>> ALU_Block
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xelab  -wto 301024b189554e7993e55fcad0741d65 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L work -L unisims_ver -L unimacro_ver -L secureip --snapshot controUnit_TestBench_behav work.controUnit_TestBench work.glbl -log elaborate.log
=======
call xelab  -wto 1cb9c0df8f744d18924e0f0f44387a95 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ALU_control_unit_testbench_behav xil_defaultlib.ALU_control_unit_testbench xil_defaultlib.glbl -log elaborate.log
>>>>>>> ALU_Block
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
