@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Sat Oct 03 20:24:17 +0530 2020
=======
REM Generated by Vivado on Sat Oct 03 14:42:04 +0400 2020
>>>>>>> 2716acef7a73262cb8919bc600a31eb6ce796d0a
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim ALU_control_unit_testbench_behav -key {Behavioral:sim_1:Functional:ALU_control_unit_testbench} -tclbatch ALU_control_unit_testbench.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
